trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.13'  # Updated to match your local Python version
      
  - script: |
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest pytest-azurepipelines pytest-cov
    displayName: 'Install Dependencies'

  - script: |
      source venv/bin/activate
      python manage.py migrate
      pytest users/tests/test_views.py --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    displayName: 'Run Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'QuantumTrade Tests'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<Azure Subscription>'
      appName: 'decentralized-ai-marketplace'
      package: '.'