name: CI/CD Pipeline for Decentralized AI Marketplace

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v1

      # Step 2: Set up Docker Buildx (required for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Stored Docker username in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Stored Docker password in GitHub secrets

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/decentralized-ai-marketplace:latest .

      # Step 5: Push the image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/decentralized-ai-marketplace:latest

  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v1

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    # Step 3: Install Minikube and kubectl
    - name: Install Minikube and kubectl
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        sudo chmod +x /usr/local/bin/minikube
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        sudo chmod +x /usr/local/bin/kubectl

    # Step 4: Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker

    # Step 5: Set kubectl context to Minikube
    - name: Set kubectl context to Minikube
      run: |
        kubectl config use-context minikube

    # Step 6: Create Namespace for kubernetes
    - name: Create Kubernetes Namespace
      run: |
        kubectl create namespace quantum-trade || echo "Namespace already exists"

    # Step 7: Apply Kubernetes manifests (deployment, service, etc.)
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/quantum-trade-deployment.yml  # Path to your Kubernetes manifest

    # Step 8: Verify deployment
    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get services